# Generated by Django 2.1.7 on 2019-09-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinDesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('rate', models.TextField()),
                ('description', models.CharField(max_length=50)),
                ('rate_float', models.IntegerField()),
            ],
        ),
    ]
